"""Init

Revision ID: 144a2c8cf4bb
Revises: 055e6b752203
Create Date: 2023-03-13 09:13:31.253490

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '144a2c8cf4bb'
down_revision = '055e6b752203'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
